import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { Children } from './types'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Children) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='mt-12'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
